<a href="https://colab.research.google.com/github/pramodkumhal/Pytorch-Deep-Learning/blob/main/Pytorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
import numpy as np

In [ ]:
lst=[3,4,5,6]
arr=np.array(lst)

In [ ]:
arr

array([3, 4, 5, 6])

##Convert Numpy to Pytorch Tensor

In [ ]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6])

## Indexing similar to numpy

In [ ]:
tensors[:2]

tensor([3, 4])

In [ ]:
tensors[1:4]

tensor([4, 5, 6])

### Disadvantage of from_numpy. The array and tensor uses the same memory location

In [ ]:
tensors[3]=100

In [ ]:
tensors

tensor([  3,   4,   5, 100])

In [ ]:
arr

array([  3,   4,   5, 100])

###prevent this by using torch.tensor

In [ ]:
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100])

In [ ]:
tensor_arr[3]=120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120])
[  3   4   5 100]


In [ ]:
#zeros and ones
torch.zeros(2,3,dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [ ]:
torch.ones(2,3,dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

## Arthmetic Operation

In [ ]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [ ]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [ ]:
c = torch.zeros(3)

In [ ]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [ ]:
c

tensor([ 7.,  9., 11.])

In [ ]:
torch.add(a,b).sum()

tensor(27.)

## Dot Products and Mult Operation

In [ ]:
x = torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [ ]:
x.mul(y)

tensor([12., 20., 30.])

In [ ]:
x.dot(y) # 3*4+5*4+5*6

tensor(62.)

## Matrix Multiplication

In [ ]:
x = torch.tensor([[1,4,2],[1,5,5]],dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)

In [ ]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [ ]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [ ]:
x@y

tensor([[55., 53.],
        [90., 92.]])